### ISSUE TITLE
not starting?

### ISSUE THREAD

**Issue by CraziFuzzy** [enternoescape/opendct#342]
So, first time restarting my docker in a while, and opendct didn't restart with the new 0.5.23-1 build.  Checked the log, and I'm getting: 

> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
> at opendct.tuning.hdhomerun.HDHomeRunDiscovery.extractBroadcast(HDHomeRunDiscovery.java:580)
> at opendct.tuning.hdhomerun.HDHomeRunDiscovery.getBroadcast(HDHomeRunDiscovery.java:557)
> at opendct.tuning.discovery.discoverers.HDHomeRunDiscoverer.<init>(HDHomeRunDiscoverer.java:78)
> at opendct.Main.main(Main.java:222)

Just a quick hunch, but on a 4 byte array, shouldn't we start with i=3?

**Comment by enternoescape** [comment]
You are correct. I should have marked that with a TODO. I noticed that in the Docket containers the broadcast address is often not available. I was going to create one based on the subnet mask.

**Comment by CraziFuzzy** [comment]
I had to update the docker to enable rolling back to 0.5.22 to be able to record.. no bueno.

**Comment by enternoescape** [comment]
Yeah, that's a real noob mistake on my part. I'll get an update out later today, but it will be on the stable branch.

**Comment by enternoescape** [comment]
I lied, it might be more like sometime tomorrow.

**Comment by CraziFuzzy** [comment]
hehe, no worries man.  I'm up and running with 0.5.22, I will have to update the docker image to auto-download the latest release (since right now it downloads the latest beta... y'know, in actuality, it might be worth pushing a 0.5.24 beta along with the 0.5.24 release, so those who do not update the docker image will still get a working build.  That, or remove 0.5.23 from bintray so the broken one won't get downloaded.

**Comment by enternoescape** [comment]
I was really thinking about that. I have pulled releases that had really horrible bugs, but I can all but assure you that this one will mostly just hit Linux users and out of that subset, it will mostly be Docker users. I'll pull 0.5.22 after 0.5.23 is up. I run OpenDCT on a CentOS server that's hosting all of my redundant services, but I do play with your container from time to time to see if anything behaves funny that should be fixed.

**Comment by enternoescape** [comment]
The latest version was posted last night. I removed that code path for now. I'll come back and make it work later, but the strange thing is that despite being 0.0.0.0 it's still broadcasting correctly, so maybe it doesn't need to be addressed. It's just weird really.

**Comment by enternoescape** [comment]
On further reading, apparently that's not a problem. It's just how the Docker bridge works. I guess I'll remove that code all together.

**Comment by CraziFuzzy** [comment]
Okay, the current build of the docker will now grab from release unless told to grab from beta, seems to be working great so far.
