### ISSUE TITLE
Add periodic opendct.properties file saving.

### ISSUE THREAD

**Issue by enternoescape** [enternoescape/opendct#345]
In case things do not stop correctly, it would be nice to have this file saved because there are many changes that happen other than setting changes in the JSON interface that would be nice to have preserved despite a bad stop.

**Comment by CraziFuzzy** [comment]
Would this be any more complicated than just a very simple thread forked from the main that synchronized() saves, then sleeps?

**Comment by enternoescape** [comment]
I don't even need to do that. The main thread just idles anyway, so I would just have it wake up periodically and save. I just don't have the time to do this right now, so this like like memo get it done when I resume development.
