### ISSUE TITLE
channel lookup seems wrong, and error message missing value

### ISSUE THREAD

**Issue by simeonpilgrim** [enternoescape/opendct#360]
I have a DVBT_HDHOMERUN device, and when I try tune it I get the error message:

    HDHomeRun HDHR3-DT Tuner 11112583-0] ERROR HDHRNativeCaptureDevice - legacyTuneChannel: The channel number {} is not a valid ATSC channel.

looking at the code in `\src\main\java\opendct\capture\HDHRNativeCaptureDevice.java` line 1086

        switch (encoderDeviceType) {
            case DVBC_HDHOMERUN:
            case DVBT_HDHOMERUN:
            case ATSC_HDHOMERUN:
                if (channelNumber <= 1 || channelNumber > lookupMap.length) {
                    logger.error("legacyTuneChannel: The channel number {} is not a valid ATSC channel.");
                    return false;
                }

                fChannel = lookupMap[channelNumber].FREQUENCY;
                break;

the logger.error has the parameter capture to show the channel number but it is not passed in.

I would expect 

    logger.error("legacyTuneChannel: The channel number {} is not a valid ATSC channel.", channelNumner);
    
the prior line in the log is:

    21:32:29.395 [SageTVRequestHandler-71:HDHomeRun HDHR3-DT Tuner 11112583-0] INFO  ChannelLineup - '8746-34-1200' was remapped to '34.1200'.

so I am not sure if the 8746 is getting grabbed, or the 34

**Comment by simeonpilgrim** [comment]
and I tried to get it to build locally, but gradlew complains about  

    FAILURE: Build failed with an exception.

    * What went wrong:
    Could not determine java version from '12.0.1'.

which I understand means I have a too new of java sdk for gradle, but I am not sure how resolve this.

**Comment by emveepee** [comment]
> 
> 
> and I tried to get it to build locally, but gradlew complains about
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine java version from '12.0.1'.
> ```
> 
> which I understand means I have a too new of java sdk for gradle, but I am not sure how resolve this.

You can have multiple JAVA_HOME locations I am pretty sure I just used an older one when I did a self compile at one point rather then trying to understand the issue.

**Comment by enternoescape** [comment]
The last time I compiled this was with Java 8. I'm not surprised you've having problems that haven't been fixed for newer versions. I'm not sure how much work it will be to bring gradle up to date, so that might be its own task. I don't think the code accounts for 3 dashes, but you made a good point (indirectly) that we should be logging the number that was actually looked up. I'd have to look into it which might not be for a few weeks.

**Comment by simeonpilgrim** [comment]
> You can have multiple JAVA_HOME locations I am pretty sure I just used an older one when I did a self compile at one point rather then trying to understand the issue.
> 
> After reading enternoescape's post I now remember installing zulu java 8.4 to build the jar file

Cheers for those hints, I've generally avoided Java dev, so it's all a black box to me, but I will look into those hints, so see if I can progress this myself..

**Comment by simeonpilgrim** [comment]
> The last time I compiled this was with Java 8. I'm not surprised you've having problems that haven't been fixed for newer versions. I'm not sure how much work it will be to bring gradle up to date, so that might be its own task. 

Ya, I was thinking that might be a hole I have dug for myself. I will try avoid the whole, and see if I can get Java 8 SDK to co-exist.
I had 12 for a different project, and to be honest the nature of the problems of the tooling is much like that of C#/Python tool, but is foreign to me.

> I don't think the code accounts for 3 dashes, but you made a good point (indirectly) that we should be logging the number that was actually looked up. I'd have to look into it which might not be for a few weeks.

nod, that is one of the things I am super not sure if I've always had my HDHomeRun set-up wrong. I use a couple of tools to pull EPG and with Sage internally had to use the format 8746-34-1200, while EPG Collector would by default see them as 8746:34:1200 and in the older HDHomeRun tools with the Sage "behaviour/support" I had to do it this way, but am also not sure if I choose a none default DBA or Virtual Channel setting if I can have different/simpler maps.

There is another odness, that the channels seem to have flipped so the 1200 channel used to be on 8746-28-1200 but now in HDHomeRun Setup is on 34-1200, but if I let Sage see the internal device, I need to say use 8746-28-1200 and then with the HDhomerun config UI I can see it turns the device to 8746-34-1200 so there are mappings in place that I don't get.

So a large amount of fumbling is  trying to understand what is the "abnormality" that I have introduced.

**Comment by enternoescape** [comment]
I'm finally looking at what code path is getting us to this issue and I was just noticing that it's trying to tune using legacy methods. I assume you have a tuner that doesn't have the web interface?

**Comment by enternoescape** [comment]
I can conclude that the number being used should be the middle number to select the frequency. That being the case, I can't figure out why it said the frequency didn't exist. I guess fixing the logging will be key to seeing what it is actually doing.

**Comment by enternoescape** [comment]
While testing, I can see that the old method of tuning doesn't translate well on the more modern HDHomeRun devices. I have an ATSC device that I only use for testing and forced it into legacy mode to get a better idea of what you're seeing and while it did get the frequency correct, it never returned a list of programs.

**Comment by enternoescape** [comment]
If you can share a complete log from OpenDCT, that would be very beneficial. I need to see all the choices OpenDCT made up to the failure.

**Comment by simeonpilgrim** [comment]
so the device is (from it's web page)
```
HDHomeRun DUAL
Model: HDHR3-DT
Device ID: 11112583
Firmware: 20200225
```
in New Zealand.. 

```
CH34 - 1200 , 1 , TVNZ 1
CH34 - 1201 , 2 , TVNZ 2
```

When SageTV used local Windows driver, I had to use the channel codes '8746-34-1200' well actually it used to be `'8746-28-1200' and it still worked that way. So I was trying to get OpenDCT working with the same setup assuming it was all the same.

When I got the channel scans working found the OpenDCT expected 1, 2, etc as the channel strings, and that worked (that was with BDA Compatibility Mode: NextPVR' and Virtual Channel Table mode: Inject TVCT, but then my EPG scanning software (EPG Collector) failed to find the channels, so I went back to Auto for both those settings, and told XMLTV Importer for SageTV to remapping the channels from the EPG/Xml '8746-34-1200' form as `1` and now it is just working..

So I can roll back my channels to the '8746-34-1200' format, and roll back from my altered opendct.jar file. But really felt the logs didn't show much, thus I had added more debugging to understand where this code and the channel scanning where running/exception throwing.

**Comment by simeonpilgrim** [comment]
here's the log from tonight..

I opened the channel setup editor and previewed the channel `1` for a few seconds. I then remapped it to '8746-34-1200' and tried preview that for a while ~3 seconds, then stopped that, and remapped it back to `1` and previewed that again.
[opendct_backup.zip](https://github.com/enternoescape/opendct/files/5369956/opendct_backup.zip)

**Comment by simeonpilgrim** [comment]
also as most of the lines in that log indicate, the data stream is crazy skippy, with much data loss (green errors) seen on the pictures. Not sure if there is anything obvious to tweak to improve that.

**Comment by enternoescape** [comment]
It is legacy hardware. The only reason I can see you wanting to use OpenDCT with this device is capture device pooling. SageTV should be able to use this directly and probably with a lot fewer headaches since your config is difficult for me to test/reproduce which will make our progress slow.

When SageTV does channel scans, it uses virtual channels. I'm not really sure what the first number is for. The second number is the virtual channel and the last number is the program we want from the stream. I don't completely understand why there is so much translation. Maybe I just don't understand what is different between ATSC and DVB-T. I thought the HDHomeRun abtracted that enough that I didn't need to do anything special between the two.

**Comment by simeonpilgrim** [comment]
Oh, I had been using SageTV directly connecting to the HDHomeRun for the last 7 years, very happily. But then after a windows update it stopped working. So I went searching, and in the Sage forums someone suggested OpenDCT instead on implementing my own from scratch network decoder.

**Comment by enternoescape** [comment]
Yeah, you don't want to implement from scratch. I'll keep trying to get this working with you, but I'll need to mock up something that looks like your setup to be able to debug and fix whatever the real issue is.

**Comment by simeonpilgrim** [comment]
well I have the system "working" once I solved the what OpenDCT was expecting..

**Comment by enternoescape** [comment]
I'll try to get you a new jar with the fixed logging soon if you think that will get you closer to figuring it out on your own.

**Comment by enternoescape** [comment]
Are you saying it is working ok for you now?

**Comment by simeonpilgrim** [comment]
Yes, I have a working system. Thus have no problem.
